### ISSUE TITLE
Cache manager shutdown before flushing offset

### ISSUE THREAD

**Issue by jabolina** [gingersnap-project/db-syncer#58]
Currently, we stop the cache manager in a few ways, including by listening to the `ShutdownEvent`. When the application is shutting down and the Debezium engine stops, it will try to flush the current offset. It is possible to stop the `RemoteCacheManager` _before_ flushing the offset to the remote cache. This will raise an exception during shutdown:

```text
2022-12-28 16:49:36,320 INFO  [io.gin.cdc.rem.RemoteOffsetStore] (engine) Setting {java.nio.HeapByteBuffer[pos=0 lim=29 cap=29]=java.nio.HeapByteBuffer[pos=0 lim=54 cap=54]}
2022-12-28 16:49:36,321 INFO  [org.inf.HOTROD] (engine) ISPN004002: Cannot perform operations on a cache associated with an unstarted RemoteCacheManager. Use RemoteCacheManager.start before using the remote cache.
2022-12-28 16:49:36,323 INFO  [io.gin.cdc.rem.RemoteOffsetStore] (engine) Stopping remote offset store.
2022-12-28 16:49:36,325 INFO  [io.deb.emb.EmbeddedEngine] (main) Stopping the embedded engine
2022-12-28 16:49:36,325 INFO  [io.deb.emb.EmbeddedEngine] (main) Waiting for PT5M for connector to stop
2022-12-28 16:49:36,325 ERROR [io.gin.hea.ConnectorReadiness] (engine) Engine rule1 failed [Error Occurred After Shutdown]: org.infinispan.client.hotrod.exceptions.RemoteCacheManagerNotStartedException:: Cannot perform operations on a cache associated with an unstarted RemoteCacheManager. Use RemoteCacheManager.start before using the remote cache.
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.assertRemoteCacheManagerIsStarted(RemoteCacheImpl.java:587)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.putAllAsync(RemoteCacheImpl.java:255)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.putAllAsync(RemoteCacheSupport.java:53)
	at io.gingersnapproject.cdc.cache.hotrod.HotRodOffsetBackend.set(HotRodOffsetBackend.java:38)
	at io.gingersnapproject.cdc.remote.RemoteOffsetStore.set(RemoteOffsetStore.java:51)
	at org.apache.kafka.connect.storage.OffsetStorageWriter.doFlush(OffsetStorageWriter.java:175)
	at io.debezium.embedded.EmbeddedEngine.commitOffsets(EmbeddedEngine.java:1059)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:910)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:195)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

We should handle this scenario and only stop the cache manager after the Debezium engine stopped and the offset was flushed. We can use the `RemoteOffsetStore#stop` and issue an event while the cache manager waits for an event from all created caches before stopping.

**Comment by jabolina** [comment]
I'll take an approach here of a single `CacheService` and multiple `CacheBackend`, that is, one cache per rule. In case of failure, we can stop a specific backend instead of the whole cache service. Since we are pointing to the same Hot Rod server, all backends will start failing, but each is stopped independently.

After receiving a shutdown signal, the `CacheService` only stops after all backends are disconnected.
